---
- hosts: localhost
  vars:
    hashi_apps:
      - name: terraform
        ver: 1.2.3
      - name: vault
        ver: 1.11.0
    azurecli_ver: 2.37.0
  roles:
    - role: andrewrothstein.git
    - role: andrewrothstein.hashi
  tasks:
    - name: install azurecli with pip
      pip:
        name: azure-cli=={{ azurecli_ver }}

