---
- hosts: localhost
  vars:
    hashi_apps:
      - name: terraform
        ver: 1.5.7
      - name: vault
        ver: 1.16.0
    # https://github.com/Azure/azure-cli/releases
    azurecli_ver: 2.58.0
    go_ver: 1.20.3
    jq_ver: 1.7.1
    yq_version: 4.43.1
  roles:
    - role: andrewrothstein.git
    - role: andrewrothstein.jq
    - role: andrewrothstein.yq
    - role: andrewrothstein.hashi
    - role: andrewrothstein.go
  tasks:
    - name: install azurecli with pip
      pip:
        name: azure-cli=={{ azurecli_ver }}
