---
- hosts: localhost
  vars:
    hashi_apps:
      - name: terraform
        ver: 1.5.7
      - name: vault
        ver: 1.16.0
    azurecli_ver: 2.48.1
    go_ver: 1.20.3
    jq_ver: 1.6
    yq_ver: 4.33.3
  roles:
    - role: andrewrothstein.git
    - role: andrewrothstein.jq
    - role: andrewrothstein.yq
    - role: andrewrothstein.hashi
    - role: andrewrothstein.go
  tasks:
    - name: install azurecli with pip
      pip:
        name: azure-cli=={{ azurecli_ver }}
