---
- role: andrewrothstein.hashi
  version: v1.0.14
- role: andrewrothstein.git
  version: v3.2.10
- role: andrewrothstein.jq
  version: v2.0.0
- role: andrewrothstein.yq
  version: v2.2.7
- role: andrewrothstein.go
  version: v2.4.12
