---
- role: andrewrothstein.hashi
  version: v1.0.4
- role: andrewrothstein.git
  version: v3.2.3
- role: andrewrothstein.jq
  version: v1.0.10
- role: andrewrothstein.yq
  version: v2.1.13
- role: andrewrothstein.go
  version: v2.3.11
